networks:
  mailcow-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "172.22.1.0/24"
          gateway: "172.22.1.1"
        - subnet: "2001:41d0:a:2d3b:11::/80" 
          gateway: "2001:41d0:a:2d3b:11::1"
    driver_opts:
      com.docker.network.bridge.name: 'mailcow-network'
      com.docker.network.bridge.enable_icc: "true" 
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.driver.mtu: "1500"
  default:
    external:
      name: "k_KevNet"
